name: Main Branch CI

on:
  push:
    branches: [ main ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest
    
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: set up environment
        run: cp .env.example .env

      - name: build Docker image
        run: docker build --target testing -t alpesone-app .

      - name: execute tests
        run: >
          docker run --rm
          -e APP_ENV=testing
          -e APP_KEY=base64:AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=
          alpesone-app
          composer test

      - name: notify if failed
        if: ${{ failure() }}
        run: echo "Tests failed"

  deploy:
    needs: laravel-tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to Production
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ubuntu/alpesone-challenge
            
            git pull origin main
            
            docker compose -f docker-compose.prod.yml up -d --build
            docker compose exec app php artisan migrate --force
            docker compose exec app php artisan config:cache
            docker compose exec app php artisan route:cache
            
            docker image prune -f
